/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : Role,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : Role,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };